### ISSUE TITLE
Calendar index takes an extremely long time to load on staging and shows unformatted messages

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1182]
**Describe the bug**

As title

**To Reproduce**

1. Go to https://admin.placecal-staging.org/calendars
2. See error

**Screenshots**

<img width="1529" alt="Screenshot 2022-04-27 at 13 11 35" src="https://user-images.githubusercontent.com/511734/165515478-d9f812d6-cf6a-44f8-b25b-609780c5a925.png">

**Comment by alexandria-gfsc** [comment]
This is caused by Datatables pre-rendering a html page with the raw fields. That pre-render displays while Datatables loads, and the extra data in `notices` means datatables takes longer to load, I think. Solution is basically to remove notices from the fields list or add a derivative property of `notices` to the Calendar model that updates on save
