### ISSUE TITLE
[Bug]: Password reset redirects you to root url on success

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1327]
## Description

After password reset, you get redirected to placecal.org

## Steps to reproduce

1. Click forgot pw
2. Fill in form
3. You're on placecal.org

## What you expected to happen

password reset should redirect you to the login page.

enter new password (accept invitation) should take you to the admin page.

## Implementation plan
- [ ] look at devise passwords controller and try to figure out how the redirect URL is generated
- [ ] make some tests covering this?

**Comment by ivankocienski** [comment]
That is how it should work?

1. go to 'log in'
2. click 'forgot password'
3. fill in email address
4. click 'next'
5. be taken to placecal (should be placecal log in page)

because
1. get email with reset password instructions
2. click link in email
3. be taken to 'new password' form
4. fill in, click 'nexr'
5. become logged in and taken to the admin dashboard

**Comment by kimadactyl** [comment]
Ah, the last step there didn't work for me. Instead of being taken to the admin dashboard I got taken to placecal.org. I can try again next week or @katjam can check too

**Comment by katjam** [comment]
Verified on staging.

Reset password to login form.
Password Reset link went to site admin on submit.
https://admin.placecal-staging.org/sites/default-site/edit
![image](https://user-images.githubusercontent.com/861172/181272964-59eb2f08-6745-4016-887f-c01ace739351.png)
