### ISSUE TITLE
Fix flaky test `CreateAdminUsersTest#test_visiting_the_index`

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1538]
## Description

Fix the flaky test that sometimes causes CI to fail:

```
Error:
CreateAdminUsersTest#test_visiting_the_index:
Capybara::ElementNotFound: Unable to find field "First name" that is not disabled
    test/system/create_admin_users_test.rb:35:in `block in <class:CreateAdminUsersTest>'
```

**Comment by ivan-kocienski-gfsc** [comment]
https://github.com/publiclab/plots2/issues/5683 seems to elucidate the problem and a potential solution

**Comment by erbridge** [comment]
@ivan-kocienski-gfsc It looks like they're describing a long running installation causing one test to fail because it's lazy installing something. I don't think that's the case for us.

**Comment by ivan-kocienski-gfsc** [comment]
So I think the problem is: some system tests have code like:

```ruby
click_link "thing"
found = select2_find_element
assert_empty found
```

and the `select2_find_element` does a CSS filter on the selinium page. So it looks for a match and finds none but as the timeout hasn't been reached it waits and tries again (the page/js may not have finished doing their things). Eventually the timeout is reached and it responds with no matching elements which is the correct value. But it had to wait for that.

The solution is to either put in some filler data (instead of looking for one item and expecting zero, put in two items and only expect one) or to move the tests out of system tests and into unit tests and only verify very very basic UI elements in system tests. (they should only be testing the very high level UX)

**Comment by ivan-kocienski-gfsc** [comment]
Is this still a problem on our CI?
