### ISSUE TITLE
[Bug]: digitalocean giving memory warnings

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1584]
## Description

What were you doing?

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by katjam** [comment]
@r-ferrier In case you were thinking of adding info or research regarding that memory issue - here is an issue we made earlier!

**Comment by r-ferrier** [comment]
We did some work a while back which has helped to mitigate this, by only running the calendar importer once every hour instead of every 10 minutes. This initially immediately improved the load & bandwidth, but the high memory usage persists. The screenshots below are from then, over 14 days.

<img width="1019" alt="Screenshot_2023-08-29_at_09 17 27" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/62fbb709-9510-466b-909f-26de34e2d1ae">

<img width="996" alt="Screenshot_2023-08-29_at_09 17 35" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/e954c135-7365-4d0c-86bb-6fbc3d76561b">

We are using 100% of our CPU all the time. What does it mean!
The screenshots below are from today, over 24 hours.

![Screenshot 2024-01-30 at 09 43 11](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/a014dfb9-9a47-4c96-9f40-dd148d01b41e)

![Screenshot 2024-01-30 at 09 42 57](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/f533c588-efb7-4fc2-966c-d0b19203785c)

The screenshots below here are from today, over 14 days.

![Screenshot 2024-01-30 at 09 42 47](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/f3b5bb23-aee1-4aa7-8a60-41bdc8ad05d8)

![Screenshot 2024-01-30 at 09 42 33](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/aa4ea692-d50c-49af-8203-846b4879cb62)

We think it would still be good to keep an eye on this but are interested to see how it looks following the next release which includes a ruby upgrade, which should use less memory. I've made reminders to check back 24 hrs, 1 week, and 2 weeks after this to see if there is any difference.

**Comment by r-ferrier** [comment]
This is looking a little improved since the ruby upgrade:

![Screenshot 2024-02-13 at 12 07 59](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/f8ed30bf-641b-4977-a565-5224948a44de)

Am closing this for now but will take a look in another month again to see if there has been any more change or if things are still consistent

**Comment by r-ferrier** [comment]
Oh my goodness, what a difference!

Since finding and removing [this security flaw](https://www.notion.so/gfsc/Placecal-crypto-mining-malware-57af6dc32df04298b559164cca73c7b5), CPU usage has dropped back down to an average of <10% and memory usage is back down to 60%. Everything is looking much healthier.
<img width="999" alt="Screenshot 2024-03-26 at 14 35 23" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/b018a836-7f2e-4476-accf-72c6c4a4fa3c">
<img width="1001" alt="Screenshot 2024-03-26 at 14 35 16" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/dd6dec4a-3c17-494b-9241-86156ab519f6">
<img width="1001" alt="Screenshot 2024-03-26 at 14 35 08" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/b6eacf78-32c6-4ccc-99c0-27fad164f023">
