### ISSUE TITLE
DB timeout on production (via Rollbar)

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1666]
https://rollbar.com/gfsc/placecal-production/items/239/

Database is timing out. We should find out why. How often is it happening.

**Comment by kimadactyl** [comment]
Oooh no I think this is a bone fide problem we need to track down - I think it's good we get notified about this

**Comment by r-ferrier** [comment]
Dug into this this morning:

<img width="1327" alt="Screenshot 2024-01-15 at 09 57 33" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/0ce6c0d6-3954-44ec-abc5-62b35a3dc776">

<img width="1322" alt="Screenshot 2024-01-15 at 09 57 48" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/c207c570-8d81-409c-bed1-51c346cb19f5">

A large swathe of these occurences are just routing errors caused by bots. Suggest we should ignore routing errors as they're not an especially useful thing for us to monitor from rollbar anyway.

https://docs.rollbar.com/docs/filter-or-ignore-errors-from-bots

**Comment by katjam** [comment]
Sounds like an excellent idea

**Comment by ivan-kocienski-gfsc** [comment]
verified in code - will need to monitor to see if this is fixed on staging / production
