### ISSUE TITLE
Add logging to create, edit, delete actions (for partners + maybe other entities)

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1794]
## User story

As an admin overseeing partners in an area or partnership I need to be able to see who is adding / editing partners so that I can be aware of who is contributing to the project on the ground.

Requested in Discord by PHT

## Acceptance criteria

- [ ] These are TBC - there maybe be a minimal level we can start with like logging out user id + entity id when any create, edit, delete happens.
- [ ] 

## Implementation notes & questions
![image](https://user-images.githubusercontent.com/861172/230058178-1d6f81db-91fa-498e-9793-135b4478bb40.png)

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
We had this before with [Paper Trail](https://github.com/paper-trail-gem/paper_trail) but it was creating severe performance issues and creating big db bloat. We may have implemented it naively, though.

I would quite like some plain text logs so that if we ever have a serious problem we can review it outside the app and that would solve this problem too. It also has the benefit that that's very easy to add with the core Rails Logger gem.
