### ISSUE TITLE
Allow `neighbourhood_admins` / `partnership_admin` to block partners from sites

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2047]
We want a way for partnership_admins / neighborhood_admins to be able to hide a partner from a site. This could be for a number of reasons:

- Info is out of date / misleading
- Unsure if partner still active
- Hacked / spamming
- Some form of abuse

Currently this is done directly by editing the neighborhoods or partnership tags of a partner. This removes useful info from the partner and also means that the *_admin has more power over partner than is needed, they can edit any field in the partner they can see. We want to keep data intact and leave the power to edit a partner to those explicitly assigned as partner_admin. Adding a hidden state to a partner is the first step towards that.

## Acceptance criteria

- [ ] partner has `hidden` attribute on model.
- [ ] only partners that is `hidden == false` is visible on public placecal sites
- [ ] #2220
- [ ] only `root`, `neighbourhood_admin` or `partnership_admin` can change `hidden`.
- [ ] only `root`, `neighbourhood_admin` or `partnership_admin` can change `hidden_reason`.
- [ ] partner has an `hidden_reason` attribute.
- [ ] `hidden_reason` must be given when removing a partner from a site.
- [ ] if a partner is hidden this status is shown clearly on their edit page
- [ ] they must be shown the reason for hidden
- [ ] they are given clear instructions how to get visible again
- [ ] partner admins are emailed to alert them of status change

**Comment by r-ferrier** [comment]
From this morning's discussion:


- we think this is a lot of power to give curators and we will need to scale this back eventually but it's a good stop gap to enable us to begin removing some of the other powers from neighbourhood and partnership admins, and is not totally destructive
- we need to add a carefully worded message for both admins and partners, to describe when it's appropriate to take this action, and why this action has been taken
- we need partnership admins to input a reason as to why the action has been taken
- we need to record who has hidden a partner, and show the partner the public contact info for that admin
- make it clearer in the admin screen that user details are visible to other users
- we need partners to be alerted & we (placecal/pht) also need to be alerted when someone takes this action, by email

**Comment by david-gfsc** [comment]
First attempts at text.

*Screen shown to Curator during process of hiding partner:*
"Hiding a partner is a last resort, and will remove them from *all* PlaceCal sites, not just yours. This is appropriate if a partner suddenly starts publishing things like spam or hate speech. In such cases, hiding a partner is the right action and we appreciate your help in keeping PlaceCal a safe place to be.

Hiding a partner does not delete them. It will notify both the partner and the PlaceCal team, using the information you fill out below. The partner will receive your email address in order to discuss or arrange reinstatement.

If you wish to remove a partner from your PlaceCal site only, but not others, you can remove your partnership tag from that partner. Removing a partnership tag will not notify the partner or hide them from other PlaceCal sites, just yours.

Information Required:
Reason for hiding partner: [text field]
Steps for reinstatement: [text field]"


*Message to partner:*
"[partner],

Your organisation has been hidden from PlaceCal, by the admin of [site].

The reason given is:
[text]

To reverse this action, they say you will need to:
[text]

You can contact them to discuss this via [curator email]

If you feel this was in error, or that the [site] Admins are being unreasonable, you can raise a support ticket with PlaceCal here: [chatwoot link/email/form]"
