### ISSUE TITLE
Allow partnership admins to add partners into partnerships without being given any extra powers

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2050]
## Description

A `tag_admin` cannot see or interact with any partners unless they become a `neigbourhood_admin` / `partner_admin`

There is no reason we hide the existence of partners from them because they are currently all public listings

we should just able to show them the public details and give them the option to add the tag they control

**Comment by kimadactyl** [comment]
Don't disagree but this isn't currently a problem for any users we currently have afaik. It will be an issue when we have 2 people with overlapping partnerships though.

To date I have done this once manually, adding GMSC partners that already existed to that partnership. I'm not aware of any other overlap.

**Comment by kimadactyl** [comment]
Actually i think as is this is a security issue as people could add partners to their partnership in order to fuck with them

**Comment by katjam** [comment]
This does not need to be a security flaw and could be solved with the proposed handshake system - request a patner / request to be added to a partnership - 2 way agreement.

**Comment by r-ferrier** [comment]
superseded by more fine grain breakdown of permissions required in other tickets. We also think the crux of the issue in this ticket is that we thought partnership admins should not also have to have neighbourhood permissions in order to do the things they need to do, but we've since agreed that partnerships admins will always need to be neighbourhood admins too.
