### ISSUE TITLE
[Bug]: Adding duplicate service areas causes a db crash

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2057]
## Description

If you try to save a partner and add two service areas that are the same service area at once, db borks

## AC

- [ ] You cannot submit a form with duplicate service areas

## plan

There is not an easy / obvious way to modify the `add service area` button to show a filtered list of options based on the previous time the form was updated.

So I will filter the params at the controller, to ensure they are unique. This is probably safer anyway because it also means the any API requests are dealt with, relying on server validation instead of client validation.

**Comment by aaaaargZombies** [comment]
Trying to reproduce

- can have service area and address as same neighbourhood, in this case Hulme
- attempt to add second service area of Hulme and we get a reasonable error and no crash

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/6f2bb6f7-c570-4999-9f16-4e976d702ead)

- tried adding two identical service areas not shared by address. Address = hulme, service areas = Abbey,Abbey

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/26899ad2-a862-42ce-a0fe-24410db6fe5d)

- trying with `citizen partner_admin` rather than root . Address = West End - (2019/12), service areas = Abbey, Abbey

![2023-09-19-10:10:47-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/55d74acc-2557-4bbf-bb1f-dead3be8d3d0)

**Comment by aaaaargZombies** [comment]
Reproduced on **burnt roti** by adding two new service areas of **Abbey, Buckinghamshire** 

```
ActiveRecord::RecordNotUnique at /partners/burnt-roti

PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_service_areas_on_neighbourhood_id_and_partner_id"
DETAIL:  Key (neighbourhood_id, partner_id)=(20649, 238) already exists.
```

If you add one, save it, then try to add the second we catch the error more gracefully

**Comment by aaaaargZombies** [comment]
## verified


https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/7f208b86-bd89-4cd0-a89c-eee0beeafdb3
