### ISSUE TITLE
[Bug]:  `tag_admin` should only be relevant to partnership tags

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2061]
## Description

a `tag_admin` is created by assigning a tag to a user, this is used to add partners onto sites that are interest based communities.

## AC

- [ ] Replace all string mentions of "tag admin" in the admin interface to "partnership admin"
- [ ] Generally stop using the term "tag admin" to refer to partnership admins
- [ ] only partnership-type tags can be assigned and unassigned to users
- [ ] the only people who can change partnership assignments are `root`
- [ ] `root` users can edit partnerships
- [ ] partnership_admins can edit their specific partnerships
- [ ] noone else can edit partnerships
- [ ] only `root` users can create partnerships
- [ ] only `root` users can delete partnerships
- [ ] ~~everyone can otherwise see all partnerships?~~
- [ ] ensure this is reflected in the documentation

## developers plan

- first change UI strings in admin interface
- limit scope of assigning tags to users to partnership tags
- adjust user privileges
- add tests to confirm / protect AC
- update docs on notion

**Comment by kimadactyl** [comment]
looks good to me, i think the fact partnerships inherit from tags is a backend irrelevance and anything we can do to make that clearer is good

**Comment by ivan-kocienski-gfsc** [comment]
Does this issue cover the Site admin page?

![Screenshot_2023-09-29_10-56-38](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/69a07e87-caf8-416d-8576-73d4a58cd7f4)

**Comment by ivan-kocienski-gfsc** [comment]
I am having a go at clarifying the AC here:

- [ ] Replace all string mentions of "tag admin" in the admin interface to "partnership admin" (for users and partner pages)
- [ ] Generally stop using the term "tag admin" to refer to partnership admins
- [ ] only partnership-type tags can be assigned and unassigned to users
- [ ] the only people who can change partnership assignments are `root` (assignments? you mean applying partnership tags to users / partners - i thought this is what a partnership admin will do)
- [ ] `root` users can edit partnerships (the tags or the links between users and partners (and sites))
- [ ] partnership_admins can edit their specific partnerships (the tags or the joins?)
- [ ] noone else can edit partnerships (the tags or the joins?)
- [ ] only `root` users can create partnerships (the tags)
- [ ] only `root` users can delete partnerships (the tags
- [ ] ~~everyone can otherwise see all partnerships?~~
- [ ] ensure this is reflected in the documentation

**Comment by aaaaargZombies** [comment]
> Does this issue cover the Site admin page?
> 
> ![Screenshot_2023-09-29_10-56-38](https://user-images.githubusercontent.com/109223824/271535811-69a07e87-caf8-416d-8576-73d4a58cd7f4.png)

hmmm it doesn't look like it from the AC but I would say the rule of thumb is, `partnership_admin` can only apply the partnership tags they have been assigned by a root in their profile.

So if it's limiting them to that on the site page then good, if they can include anyone from a tag they don't admin bad.

**Comment by aaaaargZombies** [comment]
> the only people who can change partnership assignments are root (assignments? you mean applying partnership tags to users / partners - i thought this is what a partnership admin will do)

So it should be

- `root` can allow a `citizen` access to a partnership tag, making them a `partnership_admin`
- `partnership_admins` can assign the partnership tag they have access to, to partners, thus adding them to a site with the tag filtering like transDim
