### ISSUE TITLE
[Bug]: Remove random json emissions

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2065]
## Description

Some pages are emitting random json:

https://trans-dimension.placecal.org/partners.json

We should remove this!

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by katjam** [comment]
Closing as part of #2097

**Comment by ivan-kocienski-gfsc** [comment]
Reopenning as #2097 is just a research issue and no longer fixes the problem

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I suggest we close this again. It is part of that other issue. Yes, the research needs doing first, but a plan should follow from the research. The Acceptance Criteria of that other issue encompasses this which is:

"No data that should not be public is exposed" and further "All data we expose in APIs is intentional"
