### ISSUE TITLE
A site_admin can Configure key info about the Neighbourhood PlaceCal site (homepage information on norwich.placecal.org including logos etc.)

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2108]
Needs verifying/ need to check there isn't anything you can change you shouldn't be able to change

## desired permissions / AC

- [ ] only have access to site they are admin of
- [ ] fix broken UI for none Root users (see screenshot in comments)
- [ ] explain what badge zoom is to users (see comments)
- [ ] all details remain visible even if there is no permission to edit them
- [ ] table is true

Attribute | Root | site_admin | verified/ticketed
| ---|---|---|---
| `badge_zoom_level` | ✅ | ✅ | ✅ | 
| `description` | ✅ | ✅ |  ✅ |
| `footer_logo` | ✅ | ✅ |  ✅ |
| `hero_image_credit` | ✅ | ✅ | ✅ | 
| `hero_image` | ✅ | ✅ | ✅ | 
| `hero_text` | ✅ | ✅ | ✅ | 
| `logo` | ✅ | ✅ | ✅ | ✅ | 
| `name` | ✅ | ✅ |✅ | 
| `place_name` | ✅ | ✅ | ✅ | 
| `tagline` | ✅ | ✅ | ✅ | 
| `theme` | ✅ | ✅ | ✅ | 
| `is_published`  | ✅ | ✅  | ✅ | 
| "other neighbourhoods" | ✅ | ❌ | ✅  |
| "tags" -> "partnerships" | ✅ | ❌ |  ✅  |
| `domain` | ✅ | ❌ | ✅  |
| `site_admin_id` | ✅ | ❌ |  ✅  |
| `slug` | ✅ | ❌ | ✅  |
| "main neighbourhood" | ❌ | ❌ | ✅ |

Note that main neighbourhood is not editable as this was causing issues in the past and it seemed easier to delete and remake. It may be this is no longer an issue.

**Comment by kimadactyl** [comment]
i think they deffo need control over `is_published` 

deffo don't let them edit `slug` (and in geneal i think only let roots edit slugs)

i can see the case for `badge_zoom_level` too but also see the case for not

`theme` is a weird one as if we make them logos in one colour and they change it itll obviously look bad but maybe thats their problem

otherwise looks good :)

**Comment by kimadactyl** [comment]
just to note i think they need to be able to **view** all the fields tho still.

**Comment by aaaaargZombies** [comment]
`badge_zoom_level`  relates to the lozenge in the public UI ie, manchester or hulme

The admin UI could be clearer.

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/87772c5f-969c-4774-b051-ea4120956796)

**Comment by aaaaargZombies** [comment]
broken site_admin ui

![admin placecal-staging org_sites_hulme_edit](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/73b9c5cd-01e8-4575-9d1f-2d5eda4f736f)

**Comment by kimadactyl** [comment]
also `tags` should be renamed `partnerships`

**Comment by aaaaargZombies** [comment]
weird behavior, if a root adds another neighbourhood to the site

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/6c456127-a938-4ab9-aa62-489f31872b0c)


but the user is not a neighbourhood_admin for that neighbourhood it shows up incorrectly - presumably because they aren't allowed to see it.

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/6ea0d1f8-e78a-40d1-be67-1c4591e73eaf)


I guess this is the responsibility of the Root to not create a site where the admin is not  neighbourhood_admin for the areas it encompasses

I have captured this as an issue here #2115

**Comment by kimadactyl** [comment]
Good catch - yeah at the moment this is 2 steps you have to do manually and one day it would be good to remove it but for now we are doing this rarely and always by an admin?

**Comment by r-ferrier** [comment]
Verified:

- no more broken UI for Neighbourhood Admin & scales as it should:
<img width="930" alt="Screenshot 2023-11-09 at 09 32 44" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/7477e554-88e6-4573-944c-5dc648789ca6">

- nice little badge zoom explanation
![Uploading Screenshot 2023-11-09 at 09.34.37.png…]()

- uneditable bits still visible
<img width="605" alt="Screenshot 2023-11-09 at 09 34 41" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/cdb1bfbc-41d9-46a1-a7e6-22793b4ee85f">

- tags are now called partnerships
<img width="655" alt="Screenshot 2023-11-09 at 09 38 43" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/4f2c3152-908c-40aa-a805-6a333a573b55">

- everything editable as neighbourhood admin except other neighbourhoods, partnerships, domain, site_admin_id, slug, main neighbourhood
![admin placecal-staging org_sites_test_edit (1)](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/1ab445ee-71f4-408f-9ad0-723e9c639c4f)

- everything editable as a root except main neighbourhood
![admin placecal-staging org_sites_test_edit](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/e4e62663-88b0-4a5a-a176-c27d39337610)
