### ISSUE TITLE
Partnership admins can delete partners that ONLY have service areas/addresses within their neighbourhood scope and tags that they admin for

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2177]
This is to prevent the deletion of partners still operating in other neighbourhoods/ partnerships.

## Acceptance criteria

- [x] A partnership admin can delete a partner whose service area, address, and partnership tag they admin for
- [x] A partnership admin cannot delete a partner whose service area they do not admin for
- [x] A partnership admin cannot delete a partner whose address they do not admin for
- [ ] A partnership admin cannot delete a partner whose partnership tag they do not admin for

**Comment by r-ferrier** [comment]
This is blocked by #2168

**Comment by ivan-kocienski-gfsc** [comment]
@r-ferrier question about spec:

does a partnership admin user need to own `ALL` the service area neighbourhoods or is it a `ANY` service area check?

same question for tags: does the PA user need to own `ALL` the partnership tags on that partner or `ANY` partnership tag?

are these checks `OR` or `AND`? so does a PA admin need to own all the service areas AND address AND tags?

**Comment by katjam** [comment]
Someone else should confirm but my understanding is:
A partnership admin can delete a partner if that partner is not a valid partner in another partnership. e.g. They have exactly one Partnership tag and it belongs to this admin & they operate entirely within the Service area of which this Partnership admin is a Neighbourhood admin.

The use case for this is a Partner added by a Partnership admin that is no longer active and in that case they should be able to remove them - as long as they have not since been included in another Partnership or moved (address or service area) to another Neighbourhood.

In future, it maybe should be up to the Partner whether they want to remain in PlaceCal as a neighbourhood partner and a Partnership admin should be able only to remove their tag?

**Comment by r-ferrier** [comment]
What katja said:

In order to remove a partner, a partnership admin must be the only partnership or neighbourhood admin responsible for that partner - it must not have any service areas, addresses, or partnership tags they do not admin for in order to qualify as deletable.

**Comment by r-ferrier** [comment]
Not quite working - can't delete a partner who has neighbourhoods outside of partnership scope, but CAN delete a user with partnership tags outside of scope

![admin placecal-staging org_partners_rosie-partner-with-someone-else-s-service-area_edit (1)](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/c76db88f-9ce2-4e6e-bda9-4bdbbab7598f)

**Comment by r-ferrier** [comment]
oh this actually does work! It's just cleverer than me!

You can only delete partners that no one else is a partnership admin for, ie partners with tags AND neighbourhoods that mean in combination, they are in someone else's partnership.

![Screenshot 2024-02-01 at 11 01 22](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/52b263ef-0bc6-4e6d-ba30-a96f1ec320b5)
