### ISSUE TITLE
[Bug]: partnership_admin user scope does not include users they also admin a partner with

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2212]
## Description

It is possible that a partnership_admin may also be working as a partner_admin for an partner that has not tag or neighbourhood relationship to their partnership.

They should still be able to see users which they share a connection to through joint partner_admin of a partner.

eg

PA for transdim is also involved in nottingham bog trotters. They should be able to see fellow nottingham bog trotters admins even though they have no connection to the transdim.

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by r-ferrier** [comment]
verified:

partner admins can see partners in their neighbourhood with their tag AND partners they admin for who they would not otherwise be able to see

<img width="886" alt="Screenshot 2024-01-31 at 13 11 00" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/b746c146-5e81-4ba5-ac27-77048174d0bd">

neighbourhood admins can see partners in their neighbourhood AND partners they admin for outside of their neighbourhood

<img width="1241" alt="Screenshot 2024-01-31 at 13 13 01" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/178e2e11-b446-4a90-b65b-30a783e1ec56">
