### ISSUE TITLE
[Bug]: instance homepage - text on images lacking sufficient contrast

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2314]
## Description

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/25aa6d4d-baec-49dc-83b2-3163372c144d)

## AC

- [ ] hero image component is created (if no suitable component already exists)
- [ ] text is moved below image
- [ ] hero component and text component match marks design
- [ ] remaining content is still visible in section below
- [ ] "Image credit: John Smith" (small change from design requested by Kim)
- [ ] guidance in admin UI for users uploading image (size / format)
- [ ] #2325

## implementation details

see Marks alternate design

https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/screen/719bd483-3cf9-47ef-a4ca-e2ec91c1f951/

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/07511bba-bef3-4ba4-b046-058d73c3e533)

This not an implementation of the entire page, just the hero image component so move the existing text on the white background down into the beige area.

![plan](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/62d69865-0a76-48ab-8998-0ad523c99cf5)

**Comment by kimadactyl** [comment]
This is `eee` for me as it also allows people to upload whatever image they want unsupervised - right now we have to process all these ourselves

**Comment by kimadactyl** [comment]
Tiny change lets make the text just "Image credit: John Smith", the "of" there is a lil odd to me

> This not an implementation of the entire page, just the hero image component so move the existing text on the white background down into the beige area.

do you mean, the design doesnt have the full page implementation or you dont want to implement the full page? i can see the full page design on the link, just checking somethings not gone awry.

it would be really nice to have the whole design implemented but understand if thats not trivial - its been way too long since i did any css but im worried about you getting a bit in knots trying to implement half a design if you get me. i think the grid is exactly the same its the colours that have changed but thats very easy to say from this distance of working on the code base.

**Comment by aaaaargZombies** [comment]
![hero_image_guide](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/d2545eaa-55de-429f-904a-dee05d15d795)

Just attaching this so we can reference it later in docs

the 2:1 aspect ratio is mobile view, the slimmer 3:1 aspect ratio is for desktop. This is visual is to help people select images that will be cropped differently at different view ports.

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

## Image as appears on site landing page
![Screenshot_2024-04-04_14-34-14](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/9759b9a1-4994-401e-8d9a-bcf23b9ff875)


## Partner admin edit fields
![Screenshot_2024-04-04_14-34-57](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/d1ce71ed-c89d-453d-8665-ee0405df9b5a)
