### ISSUE TITLE
[Bug]: Can't delete the duplicate "the proud trust"

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2451]
## Description

Attempting to delete an old dupe of The Proud Trust and getting an error.

## Steps to reproduce

1. Go here: https://admin.placecal.org/partners/the-proud-trust/edit
2. Scroll to bottom
3. Click "delete partner"
4. Error as shown
5. Partner still exists

<img width="896" alt="Screenshot 2024-04-29 at 16 03 10" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/32eee888-ebce-4726-8f6f-2cd3c5057db8">

## What you expected to happen

Partner is deleted

## Platform (if relevant)

What device and browser were you using?

**Comment by r-ferrier** [comment]
Once the calendar importer has rerun this should (in theory) be possible - I think it's a legacy of the old event matching system whereby events would be hooked up to partners as places, but the new system doesn't allow this

**Comment by kimadactyl** [comment]
ok will try tomorrow

**Comment by kimadactyl** [comment]
OK it worked! Do you know the root cause of this bug? Will it happen again or should we close it off?

**Comment by kimadactyl** [comment]
closing, can reopen via the rollbar log or something

**Comment by r-ferrier** [comment]
It wasn't actually a bug - but some behaviour we have changed. So previously the system would assign partners to events as they were imported if their addresses matched. This allowed events to be hooked up to partners they had no real relationship with causing all sorts of nasty edge cases like this. The importer now gives events their own addresses (except for if you're importing with the place strategy - I didn't have time to get into unpicking that) and if the address matches another partner's address, it evaluates and matches it on the fly, rather than recording it as a match in the db.

**Comment by katjam** [comment]
Won't fix / resolved itself and verified.
