### ISSUE TITLE
[Bug]: Using the category filter on the partners index is not showing partners that should be there

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2544]
## Description
Demo-ing filters for category tags on https://climatejustice.placecal.org/partners

## Steps to reproduce

1. View dropdown options - all ctegories are presented
2. Select one - no result, no empty text

## What you expected to happen

Rakesh says he has added categories, but the few partners I checked have none. I'll need to confirm with him, but this bug should be fixed either way. See #1909 

There are a lot of open issues related to filtering. This may be part of a bigger problem we want to tackle. https://github.com/geeksforsocialchange/PlaceCal/milestone/25

**Comment by kimadactyl** [comment]
That's weird - it works on the hulme site

https://hulme.placecal.org/partners

**Comment by katjam** [comment]
It may be because there are none in use, so it shows all? Though Rakesh did say he was using them... so I'll bring it up next check in.

**Comment by kimadactyl** [comment]
The filter logic I can't parse at all, it looks like it's been way way way overcomplicated to me. I'm gonna refactor it.

I don't know why we need a query anything like this complex, and what it returns doens't seem to match the function names.

https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/controllers/concerns/partner_filters.rb#L42

**Comment by kimadactyl** [comment]
OK - I found the underlying issue here and it's partly my fault!

The problem is that Rails doesn't seem to like me chaining two `where`s on the same property.

In this example, 8 is the ID for "Activism" and 28 for "Climate Justice. There is deffo a valid partner that has both. However, the implicit chaining Rails is doing is something like this:

```ruby
Partner.joins(:tags).where("tags.id in (?)", 8).where("tags.id in (?)", 28)
  Partner Load (14.8ms)  SELECT "partners".* FROM "partners" INNER JOIN "partner_tags" ON "partner_tags"."partner_id" = "partners"."id" INNER JOIN "tags" ON "tags"."id" = "partner_tags"."tag_id" WHERE (tags.id in (8)) AND (tags.id in (28)) /* loading for pp */ LIMIT $1  [["LIMIT", 11]]
```

@katjam - do you know if that SQL should be working? I'm a little out my depth here.

It's kinda my fault as there was a `for_site_with_tags` method I deleted, but I couldn't work out why it existed. Now I think I know but it's not a pretty solution to this!
