### ISSUE TITLE
Migrate stats to Plausible

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#855]
- [ ] Remove Google Analytics code
- [ ] Add following code instead

`<script defer data-domain="placecal.org" src="https://plausible.io/js/plausible.js"></script>`

This removes any need for cookie or GDPR warnings so its more important than it looks.

**Comment by kimadactyl** [comment]
I don't quite follow these docs about what to do if we want subdomains too. Unclear if we have to set up a diff tracking code in plausible for each separate subdomain or if it will just track everything under one global property.

https://plausible.io/docs/add-website

**Comment by alexandria-gfsc** [comment]
> You don't necessarily need to install the script on the same domain as
the domain you have added to your Plausible account. This allows you more
flexibility in your setup all depending on your situation. It also means
that Plausible can work with domains that feature special characters. Just
spell out the domain without using special characters when adding it to
Plausible

To me, indicates that we only need to add that script file, and then we add
domains on the frontend provided by plausible. I think I will roll this
into the datatables change since I am dealing with the frontend in this
change anyway, and it's a very quick alteration.
